language: go
sudo: true
go:
- 1.12.x
env:
  global: TARGET_HOST=https://xpau.se
before_install:
- openssl aes-256-cbc -K $encrypted_8b229560a7e3_key -iv $encrypted_8b229560a7e3_iv
  -in client-secret.json.enc -out client-secret.json -d
script:
- make install
- make test
- make build
deploy:
  provider: gae
  project: golang-app-eng
  keyfile: client-secret.json
  default: true
  skip_cleanup: true
